=== chokdee/jitty/data/src/test/resources/xml-import/TournamentPortal.dtd
<?xml encoding="UTF-8"?>
        <!--
  ~ Copyright (c) 2017.
  ~ J. Melzer
  -->

        <!--- DTD for the XML-structure used to export players of a tournament and afterwards import the result

          Version History
          2011-03-29  wh@datenautomaten.nu  1st Edition
          2017-01-26  so@datenautomaten.nu  Update lt. SPE-215
        -->

        <!--
        Datumsformat: yyyy-MM-dd
        winning-sets: Zahl, lt. Auswahl Gewinnsätze (Standard) Antrag, Schritt 2
        winning-sets-text: Text, lt. Texteingabe Gewinnsätze (Abweichung) im Antrag, Schritt 2
        table-count: Zahl, lt. Auswahl Tischanzahl im Antrag
        multiple-participations-same-day: true/false, lt. Auswahl Doppelstart am selben Tag im Antrag
        multiple-participations-same-time: true/false, lt. Auswahl Doppelstart zur selben Zeit Antrag
        team-formation: Text, lt. Auswahl Mannschaftsformation im Antrag
        -->
        <!ELEMENT tournament (tournament-location*,competition+)>
        <!ATTLIST tournament
                name CDATA #REQUIRED
                start-date CDATA #REQUIRED
                end-date CDATA #REQUIRED
                tournament-id CDATA #REQUIRED
                winning-sets CDATA #IMPLIED
                winning-sets-text CDATA #IMPLIED
                multiple-participations-same-day CDATA #IMPLIED
                multiple-participations-same-time CDATA #IMPLIED
                table-count CDATA #IMPLIED
                team-formation CDATA #IMPLIED
                >

        <!--
        Austragungsorte <tournament-location> sind optional, es kann mehrere geben, wenn keine ausgeliefert werden, sind keine vorhanden
        Alle Attribute Text lt. Eingabe im Antrag
        -->
        <!ELEMENT tournament-location EMPTY>
        <!ATTLIST tournament-location
                name CDATA #IMPLIED
                street CDATA #IMPLIED
                zip-code CDATA #IMPLIED
                city CDATA #IMPLIED
                >

        <!-- Bei der Auslieferung der Spielerliste ist <matches> nicht vorhanden.
        Beim Zurückspielen kann es vorhanden sein.
        Wenn es nicht vorhanden ist, werden die Daten der <competition> nicht verändert.

        start-date Format : yyyy-MM-dd HH:mm
        entry-fee : Startgeld der Konkurrenz lt. Eingabe im Antrag
        age-from: Jüngster Jahrgang der teilnehmen darf (abgebildet als Jahreszahl, z.B. 2010)
        age-to: Ältester Jahrgang der teilnehmen darf (abgebildet als Jahreszahl, z.B. 1999)
        sex: Geschlecht, lt. Auswahl Antrag
        preliminary-round-playmode: Austragungssystem Vorrunde lt. Auswahl/Eingabe im Antrag
        final-round-playmode: Austragungssystem Endrunde lt. Auswahl/Eingabe im Antrag
        max-persons: Maximale Teilnehmerzahl lt. Antrag
        -->
        <!ELEMENT competition (players, matches?)>
        <!ATTLIST competition
                age-group CDATA #REQUIRED
                type (Einzel|Doppel|Mixed|Mannschaft) #REQUIRED
                start-date CDATA #REQUIRED
                ttr-from CDATA #IMPLIED
                ttr-to CDATA #IMPLIED
                ttr-remarks CDATA #IMPLIED
                entry-fee CDATA #IMPLIED
                age-from CDATA #IMPLIED
                age-to CDATA #IMPLIED
                sex CDATA #IMPLIED
                preliminary-round-playmode CDATA #IMPLIED
                final-round-playmode CDATA #IMPLIED
                max-persons CDATA #IMPLIED
                >

        <!-- Wenn keine <player>-Elemente vorhanden sind, ist noch keine Spielerliste für diese Konkurrenz vorhanden.  -->
        <!ELEMENT players (player*)>

        <!-- 2e Person ist nur beim Doppelspieler vorhanden

        team-name und team-nr wird dann verwendet zur korrekte Darstellung der Mannschafts-Turniere
        -->
        <!ELEMENT player (person,person?)>
        <!ATTLIST player
                type (single|double) #REQUIRED
                id ID #REQUIRED
                team-name CDATA #IMPLIED
                team-nr CDATA #IMPLIED
                placement CDATA #IMPLIED
                >

        <!-- Verbindung von firstname, lastname, birthyear, licence-nr ist eindeutig.
            nationality: Text, zweistellg. Ländercode
            foreigner-eq-state: Text, Ausländergleichstellungsstatus, nur relevant, wenn Nationalität ungleich DE
            region: Bezirk, des Vereins bei dem die Person Mitglied ist
            sub-region: Kreis, des Vereins bei dem die Person Mitglied ist
        -->
        <!ELEMENT person EMPTY>
        <!ATTLIST person
                firstname CDATA #REQUIRED
                lastname CDATA #REQUIRED
                birthyear CDATA #REQUIRED
                internal-nr CDATA #REQUIRED
                licence-nr CDATA #REQUIRED
                sex (0|1|2) #REQUIRED
                club-name CDATA #IMPLIED
                club-nr CDATA #IMPLIED
                club-federation-nickname CDATA #IMPLIED
                ttr CDATA #IMPLIED
                ttr-match-count CDATA #IMPLIED
                nationality CDATA #IMPLIED
                foreigner-eq-state CDATA #IMPLIED
                region CDATA #IMPLIED
                sub-region CDATA #IMPLIED
                >

        <!-- leere Liste -> vorhandene Spiele werden gelöscht -> Bewerb wird zurückgesetzt.

        -->
        <!ELEMENT matches (match*)>


        <!--

        Sortierung nach Competition, match.nr, match.group.
        Gruppierung nach Competition, match.group

        IDREF: ID des Spielers muss bei dieser competition.players vorhanden sein.

        scheduled Format : yyyy-MM-dd HH:mm

        state: zeigt an ob einer der beiden Spieler aufgegeben hat (retired-a, retired-b) - optional,
        derzeit nur bei Turnierserien vorgesehen, wird sonst ignoriert, matches-a und matches-b damit konsistent sein!

        -->
        <!ELEMENT match EMPTY>
        <!ATTLIST match
                nr CDATA #IMPLIED
                group CDATA #IMPLIED
                scheduled CDATA #IMPLIED
                player-a IDREF #REQUIRED
                player-b IDREF #REQUIRED
                state (retired-a | retired-b) #IMPLIED

                set-a-1 CDATA #REQUIRED
                set-a-2 CDATA #REQUIRED
                set-a-3 CDATA #REQUIRED
                set-a-4 CDATA #REQUIRED
                set-a-5 CDATA #REQUIRED
                set-a-6 CDATA #REQUIRED
                set-a-7 CDATA #REQUIRED
                sets-a (0|1|2|3|4|5|6|7) #REQUIRED
                matches-a (0|1)  #REQUIRED
                games-a CDATA #REQUIRED

                set-b-1 CDATA #REQUIRED
                set-b-2 CDATA #REQUIRED
                set-b-3 CDATA #REQUIRED
                set-b-4 CDATA #REQUIRED
                set-b-5 CDATA #REQUIRED
                set-b-6 CDATA #REQUIRED
                set-b-7 CDATA #REQUIRED
                sets-b (0|1|2|3|4|5|6|7) #REQUIRED
                matches-b (0|1) #REQUIRED
                games-b CDATA #REQUIRED
                >

=== chokdee/jitty/web/src/test/resources/Turnierteilnehmer.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE tournament SYSTEM "http://liga.nu/dtd/TournamentPortal.dtd">
<tournament end-date="2017-03-12" multiple-participations-same-day="false" winning-sets="3" multiple-participations-same-time="false" start-date="2017-03-12" name="andro WTTV-Cup" table-count="6" tournament-id="lxnfy8egjpKwukE9myqZarSPxduPRXbs">
	
		<tournament-location/> 
	
		<tournament-location city="Sankt Augustin" zip-code="53757 " name="Sporthalle Sportzentrum Menden-Süd" street="Siegstrasse 119"/> 
	
	
		<competition start-date="2017-03-12 12:00" age-group="Damen/Herren" age-from="2017" max-persons="12" sex="gemischt" age-to="1897" type="Einzel" entry-fee="7.0" preliminary-round-playmode="Schweizer System">
			<players>
				
					<player type="single" id="PLAYER1">
						<person licence-nr="156012528" lastname="Beitel" club-name="TTG St. Augustin" sex="0" ttr-match-count="6" region="Mittelrhein" club-federation-nickname="WTTV" ttr="848" internal-nr="NU1891464" foreigner-eq-state="false" firstname="Annett" nationality="DE" club-nr="156012" birthyear="1979" sub-region="Rhein-Sieg"/>
						 
					</player>
				
					<player type="single" id="PLAYER2">
						<person licence-nr="148026208" lastname="Bosse" club-name="TTV BW Neudorf" sex="1" ttr-match-count="216" region="Düsseldorf" club-federation-nickname="WTTV" ttr="1219" internal-nr="NU210632" foreigner-eq-state="false" firstname="Gerd" nationality="DE" club-nr="148026" birthyear="1954" sub-region="Rhein-Ruhr"/>
						 
					</player>
				
					<player type="single" id="PLAYER3">
						<person licence-nr="156023461" lastname="Dauth" club-name="TTC Troisdorf" sex="1" ttr-match-count="6" region="Mittelrhein" club-federation-nickname="WTTV" ttr="1309" internal-nr="NU215803" foreigner-eq-state="false" firstname="Mario" nationality="DE" club-nr="156023" birthyear="1972" sub-region="Rhein-Sieg"/>
						 
					</player>
				
					<player type="single" id="PLAYER4">
						<person licence-nr="151052427" lastname="Jakob" club-name="1. FC Köln" sex="1" ttr-match-count="759" region="Mittelrhein" club-federation-nickname="WTTV" ttr="1474" internal-nr="NU1259860" foreigner-eq-state="false" firstname="Jonte" nationality="DE" club-nr="151052" birthyear="2002" sub-region="Köln-Erft"/>
						 
					</player>
				
					<player type="single" id="PLAYER5">
						<person licence-nr="151052426" lastname="Jakob" club-name="1. FC Köln" sex="1" ttr-match-count="564" region="Mittelrhein" club-federation-nickname="WTTV" ttr="1599" internal-nr="NU1259106" foreigner-eq-state="false" firstname="Jürgen" nationality="DE" club-nr="151052" birthyear="1968" sub-region="Köln-Erft"/>
						 
					</player>
				
					<player type="single" id="PLAYER6">
						<person licence-nr="156022071" lastname="Klein" club-name="ESV Troisdorf" sex="1" ttr-match-count="452" region="Mittelrhein" club-federation-nickname="WTTV" ttr="1353" internal-nr="NU242490" foreigner-eq-state="false" firstname="Marco" nationality="DE" club-nr="156022" birthyear="1970" sub-region="Rhein-Sieg"/>
						 
					</player>
				
					<player type="single" id="PLAYER7">
						<person licence-nr="156012521" lastname="Melzer" club-name="TTG St. Augustin" sex="1" ttr-match-count="310" region="Mittelrhein" club-federation-nickname="WTTV" ttr="1691" internal-nr="NU1429844" foreigner-eq-state="false" firstname="Jürgen" nationality="DE" club-nr="156012" birthyear="1967" sub-region="Rhein-Sieg"/>
						 
					</player>
				
					<player type="single" id="PLAYER8">
						<person licence-nr="156029301" lastname="Meuser" club-name="TSV Seelscheid" sex="1" ttr-match-count="754" region="Mittelrhein" club-federation-nickname="WTTV" ttr="1642" internal-nr="NU256262" foreigner-eq-state="false" firstname="Marcus" nationality="DE" club-nr="156029" birthyear="1972" sub-region="Rhein-Sieg"/>
						 
					</player>
				
					<player type="single" id="PLAYER9">
						<person licence-nr="156005304" lastname="Ruttka" club-name="DJK Eintracht Eitorf" sex="1" ttr-match-count="350" region="Mittelrhein" club-federation-nickname="WTTV" ttr="1477" internal-nr="NU271530" foreigner-eq-state="false" firstname="Stephan" nationality="DE" club-nr="156005" birthyear="1968" sub-region="Rhein-Sieg"/>
						 
					</player>
				
					<player type="single" id="PLAYER10">
						<person licence-nr="156012499" lastname="Sauer" club-name="TTG St. Augustin" sex="1" ttr-match-count="120" region="Mittelrhein" club-federation-nickname="WTTV" ttr="1117" internal-nr="NU1480185" foreigner-eq-state="false" firstname="Georg" nationality="DE" club-nr="156012" birthyear="1955" sub-region="Rhein-Sieg"/>
						 
					</player>
				
					<player type="single" id="PLAYER11">
						<person licence-nr="154017167" lastname="Siry" club-name="TTV Viktoria Bonn" sex="1" ttr-match-count="248" region="Mittelrhein" club-federation-nickname="WTTV" ttr="1534" internal-nr="NU281093" foreigner-eq-state="false" firstname="Manfred" nationality="DE" club-nr="154017" birthyear="1959" sub-region="Bonn"/>
						 
					</player>
				
					<player type="single" id="PLAYER12">
						<person licence-nr="156041253" lastname="Walterscheid" club-name="SSV Happerschoß" sex="1" ttr-match-count="569" region="Mittelrhein" club-federation-nickname="WTTV" ttr="1470" internal-nr="NU291226" foreigner-eq-state="false" firstname="Ingo" nationality="DE" club-nr="156041" birthyear="1972" sub-region="Rhein-Sieg"/>
						 
					</player>
				
			</players>
		</competition>
	
</tournament>
